matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8.1
      script:
        - swiftlint
        - bundle exec scripts/start_control_server.sh
        - set -o pipefail && xcodebuild test -project Phakchi.xcodeproj -scheme Phakchi -destination 'platform=iOS Simulator,name=iPhone 6' | xcpretty -c
        - bundle exec scripts/stop_control_server.sh
